config/routes.rb
FirstCrack::Application.routes.draw do

  root 'homes#index'

  resources :users, only: [:show]

  resources :items do
    resources :bids, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validate :new_highest_bid


  def new_highest_bid
    if (amount < current_highest_bid)
      errors.add(:amount, "Your bid must be higher than $#{current_highest_bid}")
    end
  end

  def current_highest_bid
    if item.bids.count == 0
      item.minimum_price
    else
      item.bids.maximum("amount")
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  has_many :bids

  private

  def self.current
    where("expiration_date > ?", Date.today)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :items
  has_many :bids
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    @item = Item.find(params[:item_id])
    @bid = @item.bids.create(bid_params)
    if @bid.valid?
      redirect_to @item
    else
      render "items/show"
    end
  end

  private

  def bid_params
    params.require(:bid).
    permit(:amount).
    merge(user_id: current_user.id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :go_to_user_page, if: :signed_in?

  def index

  end

  private
  def go_to_user_page
    redirect_to current_user
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.current
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.create(item_params)
    redirect_to @item
  end

  def show
    @item = Item.find(params[:id])
    @bid = current_user.bids.new
  end

  private

  def item_params
    params.require(:item).permit(
      :name,
      :description,
      :minimum_price,
      :expiration_date
      )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user_auction_items = current_user.items.current
    @user_bidded_on_items = current_user.bids.map(&:item).uniq
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_errors.html.erb
<% if target.errors.any? %>
  <p>Could not save for the following reasons:</p>
  <ul>
    <% target.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <%end %>
  </ul>
<% end %>

app/views/homes/index.html.erb
<h4>Welcome to First Crack</h4>

app/views/items/index.html.erb
<h2> Available Items</h2>

<%= @items.find_each do |item| %>
  <div>
    <%= link_to item.name, item %>
  </div>
  <div>
    <%= item.description %>
  </div>
  <div>
    <%= item.bids.maximum("amount") %>
  </div>
  <div>
    <%= item.expiration_date %>
  </div>
<% end %>

app/views/items/new.html.erb
<h4>What do you wish to sell?</h4>

<%= form_for(@item) do |form| %>
  <div>
    <%= form.label :name, "Item Name:" %>
    <%= form.text_field :name, placeholder: "Item name" %>
  </div>
  <div>
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description, placeholder: "Description" %>
  </div>
  <div>
    <%= form.label :image, "Image" %>
    <%= form.text_field :image, placeholder: "Image URL" %>
  </div>
  <div>
    <%= form.label :minimum_price, "Minimum Price:" %>
    <%= form.text_field :minimum_price, placeholder: "Minimum Price" %>
  </div>
  <div>
    <%= form.label :expiration_date, "Expiration Date:" %>
    <%= form.text_field :expiration_date, placeholder: "YYYY-MM-DD" %>
  </div>
    <%= form.submit "Add Item" %>
<% end %>

app/views/items/show.html.erb
<div>
  <%= @item.name %>
</div>
<div>
  Description: <%= @item.description %>
</div>
<div>
  Minimum Price: $<%= @item.minimum_price %>
</div>
<div>
  <% if @item.image.present? %>
    <%= image_tag(@item.image, width: 500) %>
  <% end %>
</div>
<div>
  The auction will end on <%= @item.expiration_date %>.
</div>

<div>
  <% if @item.bids.count == 0 %>
    There are currently no bids
  <% else %>
    The current highest bid on this item is:
    $<%= @item.bids.maximum("amount")%>
  <% end %>
</div>

<% if current_user.id != @item.user_id %>
  Place a bid on this item

  <%= form_for [@item, @bid] do |form| %>
    <%= render "form_errors", target: @bid %>
    <%= form.label :amount, "Bid Amount" %>
    <%= form.text_field :amount, placeholder: "Amount" %>
    <%= form.submit "Enter Bid" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstCrack</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <%= link_to "Home", current_user %>
  </div>

  <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= link_to 'Sign out', sign_out_path, :method => :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>


<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h3>Welcome <%= current_user.email %></h3>

<h5><%= link_to "All items for Auction", items_path %></h5>

<h5><%= link_to "Add a new Item to sell", new_item_path %></h5>

<h4>You are autioning off the following items:</h4>
<% @user_auction_items.each do |item| %>
  <div>
    <h4><%= link_to item.name, item %></h4>
    Highest current bid: $ <%= item.bids.maximum("amount") %>
    Auction ends on <%= item.expiration_date %>
  </div>
<% end %>

<h4>You have bid on the following items:</h4>

<% @user_bidded_on_items.each do |item| %>
  <div>
    <%= link_to item.name, item %>
    The highest current bid on this item is $<%= item.bids.maximum("amount") %>
  </div>
<% end %>